### ISSUE TITLE
UnboundLocalError at /evaluation1/

### ISSUE THREAD

**Issue by fzwwj95** [CAPTAIN-WHU/DOTA#17]
When submitting a file to the DOTA 1.0 Task1 evaluation server, an error is returned after the upload has finished
and haven't received any emails or response messages
<img width="789" alt="e9e526eeaa2240f0150c3f1480a31a0" src="https://user-images.githubusercontent.com/17897415/235279715-5b97f314-e34a-4b2d-96a2-ea67ceb1f42b.png">

**Comment by JinqingZhengTju** [comment]
> When submitting a file to the DOTA 1.0 Task1 evaluation server, an error is returned after the upload has finished and haven't received any emails or response messages <img alt="e9e526eeaa2240f0150c3f1480a31a0" width="789" src="https://user-images.githubusercontent.com/17897415/235279715-5b97f314-e34a-4b2d-96a2-ea67ceb1f42b.png">

How do you deal with this situation? I had the same question.
